export const adminMetrics = {
  revenue: {
    total: 'R$ 245.320',
    growth: '+12.5%',
    mtd: 'R$ 45.320',
  },
  subscriptions: {
    active: 247,
    growth: '+8',
    churn: '2.1%',
  },
  realtors: {
    active: 1243,
    newThisMonth: 87,
    avgCommission: 'R$ 2.847',
  },
  properties: {
    total: 5847,
    listed: 3421,
    sold: 847,
    leased: 1579,
  },
  users: {
    total: 4532,
    newThisMonth: 234,
    activeToday: 1342,
  },
  support: {
    openTickets: 23,
    avgResolutionTime: '4.2h',
    satisfaction: '4.8/5.0',
  },
  performance: {
    avgDealValue: 'R$ 487.500',
    conversionRate: '18.4%',
    avgTimeToSale: '42 dias',
  },
  professional: {
    usersActive: 156,
    revenue: 'R$ 77.700',
    engagement: '87%',
  },
  ai: {
    usersActive: 89,
    revenue: 'R$ 8.633',
    requestsDaily: 2847,
  },
  requests: {
    pending: 12,
    processing: 5,
    completed: 847,
  },
  audit: {
    eventsToday: 3421,
    critical: 2,
    warnings: 14,
  },
}

export const chartData = {
  revenue: [
    { month: 'Jan', value: 45000 },
    { month: 'Fev', value: 52000 },
    { month: 'Mar', value: 48000 },
    { month: 'Abr', value: 61000 },
    { month: 'Mai', value: 55000 },
    { month: 'Jun', value: 68000 },
  ],
  subscriptions: [
    { month: 'Jan', starter: 120, professional: 80, enterprise: 20 },
    { month: 'Fev', starter: 135, professional: 95, enterprise: 22 },
    { month: 'Mar', starter: 145, professional: 110, enterprise: 25 },
    { month: 'Abr', starter: 165, professional: 125, enterprise: 28 },
    { month: 'Mai', starter: 180, professional: 135, enterprise: 30 },
    { month: 'Jun', starter: 200, professional: 155, enterprise: 35 },
  ],
  churn: [
    { month: 'Jan', churn: 3.2 },
    { month: 'Fev', churn: 2.8 },
    { month: 'Mar', churn: 2.5 },
    { month: 'Abr', churn: 2.1 },
    { month: 'Mai', churn: 2.3 },
    { month: 'Jun', churn: 2.1 },
  ],
  deals: [
    { month: 'Jan', valor: 2100000 },
    { month: 'Fev', valor: 2450000 },
    { month: 'Mar', valor: 2280000 },
    { month: 'Abr', valor: 2890000 },
    { month: 'Mai', valor: 2650000 },
    { month: 'Jun', valor: 3220000 },
  ],
}

export const realtorsList = [
  {
    id: 1,
    name: 'Corretor Demonstração',
    email: 'corretor@plataforma.com.br',
    phone: '(11) 90000-0001',
    region: 'São Paulo',
    plan: 'professional',
    status: 'active',
    commissionRate: 2.5,
    totalSales: 'R$ 480.000',
    salesThisMonth: 2,
    rating: 4.9,
    joinedAt: '2026-07-01',
  },
]

export const correctorMetrics = {
  properties: {
    total: 24,
    active: 18,
    sold: 4,
    leased: 2,
  },
  sales: {
    closed: 34,
    pending: 8,
    total: 42,
    conversion: '81%',
  },
  leads: {
    new: 12,
    contacted: 8,
    qualified: 4,
    lost: 2,
  },
  revenue: {
    thisMonth: 'R$ 23.450',
    ytd: 'R$ 127.840',
    growth: '+18%',
  },
  performance: {
    avgTimeToSale: '38 dias',
    avgDealValue: 'R$ 587.500',
    commissionRate: '2.5%',
  },
  rating: {
    score: 4.8,
    reviews: 23,
    responseTime: '2.1h',
  },
  profile: {
    views: 1247,
    contacts: 234,
    conversionRate: '18.8%',
  },
  clients: {
    total: 187,
    active: 142,
    repeat: 34,
  },
}

export const propertiesList = [
  {
    id: 1,
    title: 'Apartamento Vila Mariana',
    type: 'apartment',
    status: 'published',
    price: 890000,
    area: 92,
    bedrooms: 3,
    bathrooms: 2,
    garage: 1,
    address: 'Vila Mariana, São Paulo - SP',
    image: '/api/placeholder/400/300',
    owner: { name: 'Proprietário Demo', email: 'proprietario@email.com' },
    realtor: { id: 1, name: 'Corretor Demonstração' },
    views: 320,
    contacts: 12,
    shares: 4,
    favorites: 28,
    visits: 3,
    reserved: false,
    description: 'Apartamento demonstrativo do Corretor Demonstração',
    features: ['Varanda', 'Armários embutidos', 'Próximo ao metrô'],
    createdAt: '2026-07-01',
    updatedAt: '2026-07-20',
  },
  {
    id: 2,
    title: 'Casa em Condomínio Alphaville',
    type: 'house',
    status: 'published',
    price: 1450000,
    area: 210,
    bedrooms: 4,
    bathrooms: 3,
    garage: 2,
    address: 'Alphaville, Barueri - SP',
    image: '/api/placeholder/400/300',
    owner: { name: 'Proprietário Demo 2', email: 'prop2@email.com' },
    realtor: { id: 1, name: 'Corretor Demonstração' },
    views: 210,
    contacts: 8,
    shares: 2,
    favorites: 15,
    visits: 2,
    reserved: false,
    description: 'Casa demonstrativa vinculada ao corretor seed',
    features: ['Piscina', 'Churrasqueira', 'Segurança 24h'],
    createdAt: '2026-07-05',
    updatedAt: '2026-07-22',
  },
  {
    id: 3,
    title: 'Studio Pinheiros',
    type: 'apartment',
    status: 'draft',
    price: 420000,
    area: 38,
    bedrooms: 1,
    bathrooms: 1,
    garage: 0,
    address: 'Pinheiros, São Paulo - SP',
    image: '/api/placeholder/400/300',
    owner: { name: 'Proprietário Demo 3', email: 'prop3@email.com' },
    realtor: { id: 1, name: 'Corretor Demonstração' },
    views: 40,
    contacts: 1,
    shares: 0,
    favorites: 3,
    visits: 0,
    reserved: false,
    description: 'Rascunho de imóvel para demonstração',
    features: ['Mobiliado', 'Andar alto'],
    createdAt: '2026-07-18',
    updatedAt: '2026-07-25',
  },
]
